object Libs {

    const val ACTIVITY_KTX = "androidx.activity:activity-ktx:1.1.0"
    const val APPCOMPAT = "androidx.appcompat:appcompat:1.3.1"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:2.1.1"
    const val CORE_KTX = "androidx.core:core-ktx:1.6.0"
    const val COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.1"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:1.3.6"
    const val GLIDE = "com.github.bumptech.glide:glide:4.12.0"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:4.12.0"
    const val GSON = "com.google.code.gson:gson:2.8.8"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:2.39"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler:2.39"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing:2.39"
    const val JUNIT = "junit:junit:4.13.2"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler:2.2.0"
    const val LIFECYCLE_COMMON = "androidx.lifecycle:lifecycle-common-java8:2.2.0"
    const val LIFECYCLE_EXTENSIONS = "androidx.lifecycle:lifecycle-extensions:2.2.0"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    const val MATERIAL = "com.google.android.material:material:1.4.0"
    const val MOCKITO_CORE = "org.mockito:mockito-core:3.12.4"
    const val MOCKITO_KOTLIN = "com.nhaarman:mockito-kotlin:1.6.0"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:2.9.0"
    const val RETROFIT_GSON = "com.squareup.retrofit2:converter-gson:2.4.0"

}